name: Java Spring Gradle CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        java-package: 'jdk'
        architecture: 'x64'

    - name: List directory contents
      run: ls -l

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./spring
      
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Test with Gradle
        run: |
          ./gradlew test
          ./gradlew jacocoTestReport
        working-directory: ./spring
        continue-on-error: true

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: |
            build/customJacocoReportDir/test/jacocoTestReport.xml
            build/test-results/test/

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: SonarQube Analysis with Gradle
        run: ./gradlew sonar "-Dsonar.host.url=http://localhost:9000/" "-Dsonar.login=squ_8e452817b63d478b89509ce57a913e794d0db904"
        working-directory: ./spring
        continue-on-error: true
