name: Java Spring Gradle CI with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Analyze Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: List directory contents
        run: ls -l

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./spring

      - name: Test with Gradle
        run: |
          ./gradlew test
          ./gradlew jacocoTestReport
        working-directory: ./spring

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Ensure you've set the SONAR_TOKEN in your repository secrets
        run: |
          # Execute SonarQube analysis
          sonar-scanner \
            -Dsonar.projectKey=youtubey \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN
